
language: java

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN

script:
# Remove the old dependency JARs, since they were stale for some reason.
  - ls -ltr $HOME/.m2/repository/org/onebeartoe/multimedia/1.0/multimedia-1.0.jar
  - rm $HOME/.m2/repository/org/onebeartoe/multimedia/1.0/multimedia-1.0.jar
  - rm $HOME/.m2/repository/org/onebeartoe/multimedia/1.0/multimedia-1.0.pom

  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.cfamily.build-wrapper-output=pi-ezo/target
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  
